upload_query = (
    "mutation AssetCreatePageMutation(\n  "
    "$assetContract: AssetContractRelayID\n  "
    "$collection: CollectionSlug\n  "
    "$description: String\n  $externalLink: URL\n  $identity: "
    "IdentityInputType!\n  $imageFile: Upload\n  $maxSupply: String\n  "
    "$mediaFile: Upload\n  $name: String!\n  $tokenId: String\n  $chain: "
    "ChainScalar\n  $unlockableContent: String\n  $isNsfw: Boolean!\n  "
    "$properties: [StringTraitConfig!]\n  $levels: [NumericTraitConfig!]\n  "
    "$stats: [NumericTraitConfig!]\n) {\n  assets {\n    "
    "create(assetContract: $assetContract, collection: "
    "$collection, description: $description, externalLink: "
    "$externalLink, imageFile: $imageFile, maxSupply: $maxSupply, "
    "mediaFile: $mediaFile, name: $name, tokenId: $tokenId, chain: "
    "$chain, unlockableContent: $unlockableContent, isNsfw: $isNsfw, "
    "properties: $properties, levels: $levels, stats: $stats, "
    "identity: $identity) {\n      tokenId\n      assetContract "
    "{\n        address\n        chain\n        id\n      }\n      "
    "...asset_url\n      ...itemEvents_data\n      id\n    }\n  }\n}\n\n"
    "fragment asset_url on AssetType {\n  assetContract "
    "{\n    address\n    chain\n    id\n  }\n  tokenId\n}\n\nfragment "
    "itemEvents_data on AssetType {\n  assetContract {\n    address\n    "
    "chain\n    id\n  }\n  tokenId\n}\n"
)

commit_query = (
    "query AssetPageQuery(\n  $archetype: ArchetypeInputType!\n  $chain:"
    " ChainScalar\n) {\n  archetype(archetype: $archetype) {\n    asset {"
    "\n      ...AssetCardAnnotations_asset\n      ...assetInputType\n    "
    "  ...asset_display_name\n      ...ContentAuthenticity_data\n      a"
    "ssetContract {\n        address\n        chain\n        ...Collectio"
    "nLink_assetContract\n        id\n      }\n      assetOwners(first: 1"
    ") {\n        edges {\n          node {\n            quantity\n       "
    "     owner {\n              ...AccountLink_data\n              id\n "
    "           }\n            id\n          }\n        }\n      }\n      c"
    "reator {\n        ...AccountLink_data\n        id\n      }\n      ani"
    "mationUrl\n      backgroundColor\n      collection {\n        descri"
    "ption\n        displayData {\n          cardDisplayStyle\n        }\n"
    "        hidden\n        imageUrl\n        name\n        slug\n       "
    " ...CollectionLink_collection\n        ...Boost_collection\n       "
    " ...Property_collection\n        ...NumericTrait_collection\n      "
    "  ...SocialBar_data\n        id\n      }\n      decimals\n      descr"
    "iption\n      imageUrl\n      name\n      isDelisted\n      isListabl"
    "e\n      isReportedSuspicious\n      relayId\n      tokenId\n      ha"
    "sUnlockableContent\n      favoritesCount\n      traits(first: 100) "
    "{\n        edges {\n          node {\n            relayId\n          "
    "  displayType\n            floatValue\n            intValue\n       "
    "     traitType\n            value\n            ...Boost_trait\n     "
    "       ...Property_trait\n            ...NumericTrait_trait\n      "
    "      ...Date_trait\n            id\n          }\n        }\n      }\n"
    "      ...AssetMedia_asset\n      ...EnsManualEntryModal_asset\n    "
    "  ...Toolbar_asset\n      ...asset_url\n      ...itemEvents_data\n  "
    "    ...itemEvents_viewItem_data\n      ...ChainInfo_data\n      id\n"
    "    }\n    ownedQuantity(identity: {})\n    ownershipCount\n    quan"
    "tity\n    ...TradeStation_archetype_3wquQ2\n    ...BidModalContent_"
    "archetype_3wquQ2\n  }\n  tradeSummary(archetype: $archetype) {\n    "
    "bestAsk {\n      closedAt\n      orderType\n      maker {\n        .."
    ".wallet_accountKey\n        id\n      }\n      relayId\n      id\n    "
    "}\n    ...BidModalContent_trade\n    ...TradeStation_data\n  }\n  ass"
    "etEvents(archetype: $archetype, first: 11) {\n    edges {\n      no"
    "de {\n        relayId\n        id\n      }\n    }\n  }\n}\n\nfragment Acc"
    "ountLink_data on AccountType {\n  address\n  config\n  isCompromised"
    "\n  user {\n    publicUsername\n    id\n  }\n  ...ProfileImage_data\n  "
    "...wallet_accountKey\n  ...accounts_url\n}\n\nfragment AskPrice_data "
    "on OrderV2Type {\n  dutchAuctionFinalPrice\n  openedAt\n  priceFnEnd"
    "edAt\n  makerAssetBundle {\n    assetQuantities(first: 30) {\n      "
    "edges {\n        node {\n          ...quantity_data\n          id\n  "
    "      }\n      }\n    }\n    id\n  }\n  takerAssetBundle {\n    assetQu"
    "antities(first: 1) {\n      edges {\n        node {\n          ...As"
    "setQuantity_data\n          id\n        }\n      }\n    }\n    id\n  }\n"
    "}\n\nfragment AssetCardAnnotations_asset on AssetType {\n  assetCont"
    "ract {\n    chain\n    id\n  }\n  decimals\n  relayId\n  favoritesCount"
    "\n  isDelisted\n  isFavorite\n  isFrozen\n  hasUnlockableContent\n  .."
    ".AssetCardBuyNow_data\n  orderData {\n    bestAsk {\n      orderType"
    "\n      relayId\n      maker {\n        address\n      }\n    }\n  }\n}\n"
    "\nfragment AssetCardBuyNow_data on AssetType {\n  tokenId\n  relayId"
    "\n  assetContract {\n    address\n    chain\n    id\n  }\n  collection "
    "{\n    slug\n    id\n  }\n  orderData {\n    bestAsk {\n      relayId\n "
    "   }\n  }\n}\n\nfragment AssetMedia_asset on AssetType {\n  animationU"
    "rl\n  backgroundColor\n  collection {\n    displayData {\n      cardD"
    "isplayStyle\n    }\n    id\n  }\n  isDelisted\n  imageUrl\n  displayIma"
    "geUrl\n}\n\nfragment AssetQuantity_data on AssetQuantityType {\n  ass"
    "et {\n    ...Price_data\n    id\n  }\n  quantity\n}\n\nfragment BidModal"
    "Content_archetype_3wquQ2 on ArchetypeType {\n  asset {\n    assetCo"
    "ntract {\n      address\n      chain\n      id\n    }\n    decimals\n  "
    "  relayId\n    collection {\n      slug\n      paymentAssets(chain: "
    "$chain) {\n        relayId\n        asset {\n          assetContract"
    " {\n            address\n            chain\n            id\n         "
    " }\n          decimals\n          symbol\n          usdSpotPrice\n   "
    "       relayId\n          id\n        }\n        ...PaymentTokenInpu"
    "tV2_data\n        id\n      }\n      ...verification_data\n      id\n "
    "   }\n    id\n  }\n  quantity\n  ownedQuantity(identity: {})\n}\n\nfragm"
    "ent BidModalContent_trade on TradeSummaryType {\n  bestAsk {\n    c"
    "losedAt\n    isFulfillable\n    oldOrder\n    orderType\n    relayId\n"
    "    makerAssetBundle {\n      assetQuantities(first: 30) {\n       "
    " edges {\n          node {\n            asset {\n              colle"
    "ction {\n                ...verification_data\n                id\n "
    "             }\n              id\n            }\n            id\n    "
    "      }\n        }\n      }\n      id\n    }\n    takerAssetBundle {\n "
    "     assetQuantities(first: 1) {\n        edges {\n          node {"
    "\n            quantity\n            asset {\n              decimals\n"
    "              relayId\n              id\n            }\n            "
    "id\n          }\n        }\n      }\n      id\n    }\n    id\n  }\n  best"
    "Bid {\n    relayId\n    makerAssetBundle {\n      assetQuantities(fi"
    "rst: 1) {\n        edges {\n          node {\n            quantity\n "
    "           asset {\n              decimals\n              id\n      "
    "      }\n            ...AssetQuantity_data\n            id\n        "
    "  }\n        }\n      }\n      id\n    }\n    id\n  }\n}\n\nfragment Boost"
    "_collection on CollectionType {\n  numericTraits {\n    key\n    val"
    "ue {\n      max\n      min\n    }\n  }\n  slug\n}\n\nfragment Boost_trait"
    " on TraitType {\n  displayType\n  floatValue\n  intValue\n  traitType"
    "\n}\n\nfragment ChainInfo_data on AssetType {\n  assetContract {\n    "
    "openseaVersion\n    address\n    chain\n    blockExplorerLink\n    to"
    "kenStandard\n    id\n  }\n  isEditableByOwner {\n    value\n  }\n  toke"
    "nId\n  isFrozen\n  frozenAt\n  tokenMetadata\n}\n\nfragment CollectionL"
    "ink_assetContract on AssetContractType {\n  address\n  blockExplore"
    "rLink\n}\n\nfragment CollectionLink_collection on CollectionType {\n "
    " name\n  ...collection_url\n  ...verification_data\n}\n\nfragment Coll"
    "ectionWatchlistButton_data on CollectionType {\n  relayId\n  isWatc"
    "hing\n}\n\nfragment ContentAuthenticity_data on AssetType {\n  authen"
    "ticityMetadata {\n    signedOn\n    signedBy\n    producedWith\n    w"
    "alletAddress\n    id\n  }\n  imageUrl\n  creator {\n    address\n    id"
    "\n  }\n}\n\nfragment Date_trait on TraitType {\n  traitType\n  floatVal"
    "ue\n  intValue\n}\n\nfragment EnsManualEntryModal_asset on AssetType "
    "{\n  assetContract {\n    address\n    id\n  }\n  tokenId\n}\n\nfragment "
    "NumericTrait_collection on CollectionType {\n  numericTraits {\n   "
    " key\n    value {\n      max\n      min\n    }\n  }\n  slug\n}\n\nfragment"
    " NumericTrait_trait on TraitType {\n  displayType\n  floatValue\n  i"
    "ntValue\n  maxValue\n  traitType\n}\n\nfragment PaymentAsset_data on P"
    "aymentAssetType {\n  asset {\n    assetContract {\n      chain\n     "
    " id\n    }\n    imageUrl\n    symbol\n    id\n  }\n}\n\nfragment PaymentT"
    "okenInputV2_data on PaymentAssetType {\n  relayId\n  asset {\n    de"
    "cimals\n    symbol\n    usdSpotPrice\n    id\n  }\n  ...PaymentAsset_d"
    "ata\n}\n\nfragment Price_data on AssetType {\n  decimals\n  imageUrl\n "
    " symbol\n  usdSpotPrice\n  assetContract {\n    blockExplorerLink\n  "
    "  chain\n    id\n  }\n}\n\nfragment ProfileImage_data on AccountType {"
    "\n  imageUrl\n  address\n}\n\nfragment Property_collection on Collecti"
    "onType {\n  ...collection_url\n  stats {\n    totalSupply\n    id\n  }"
    "\n}\n\nfragment Property_trait on TraitType {\n  displayType\n  traitC"
    "ount\n  traitType\n  value\n}\n\nfragment SocialBar_data on Collection"
    "Type {\n  relayId\n  discordUrl\n  externalUrl\n  instagramUsername\n "
    " mediumUsername\n  slug\n  telegramUrl\n  twitterUsername\n  ...colle"
    "ction_url\n  ...CollectionWatchlistButton_data\n}\n\nfragment Toolbar"
    "_asset on AssetType {\n  ...asset_url\n  ...itemEvents_data\n  asset"
    "Contract {\n    address\n    chain\n    id\n  }\n  collection {\n    ex"
    "ternalUrl\n    name\n    slug\n    id\n  }\n  externalLink\n  name\n  re"
    "layId\n  tokenId\n}\n\nfragment TradeStation_archetype_3wquQ2 on Arch"
    "etypeType {\n  asset {\n    assetContract {\n      chain\n      id\n  "
    "  }\n    assetOwners(first: 1) {\n      edges {\n        node {\n    "
    "      owner {\n            ...wallet_accountKey\n            id\n   "
    "       }\n          id\n        }\n      }\n    }\n    collection {\n  "
    "    ...verification_data\n      id\n    }\n    isListable\n    relayI"
    "d\n    id\n  }\n  ...BidModalContent_archetype_3wquQ2\n}\n\nfragment Tr"
    "adeStation_data on TradeSummaryType {\n  bestAsk {\n    closedAt\n  "
    "  dutchAuctionFinalPrice\n    openedAt\n    orderType\n    priceFnEn"
    "dedAt\n    englishAuctionReservePrice\n    relayId\n    maker {\n    "
    "  address\n      ...wallet_accountKey\n      id\n    }\n    makerAsse"
    "tBundle {\n      assetQuantities(first: 30) {\n        edges {\n    "
    "      node {\n            asset {\n              relayId\n          "
    "    tokenId\n              assetContract {\n                chain\n "
    "               address\n                id\n              }\n       "
    "       collection {\n                slug\n                ...verif"
    "ication_data\n                id\n              }\n              ..."
    "itemEvents_data\n              id\n            }\n            ...qua"
    "ntity_data\n            id\n          }\n        }\n      }\n      id\n"
    "    }\n    taker {\n      ...wallet_accountKey\n      id\n    }\n    t"
    "akerAssetBundle {\n      assetQuantities(first: 1) {\n        edges"
    " {\n          node {\n            quantity\n            asset {\n    "
    "          symbol\n              decimals\n              relayId\n   "
    "           usdSpotPrice\n              assetContract {\n           "
    "     address\n                id\n              }\n              tok"
    "enId\n              id\n            }\n            ...AssetQuantity_"
    "data\n            id\n          }\n        }\n      }\n      id\n    }\n"
    "    ...AskPrice_data\n    ...orderLink_data\n    ...quantity_remain"
    "ing\n    id\n  }\n  bestBid {\n    makerAssetBundle {\n      assetQuan"
    "tities(first: 1) {\n        edges {\n          node {\n            q"
    "uantity\n            ...AssetQuantity_data\n            id\n        "
    "  }\n        }\n      }\n      id\n    }\n    id\n  }\n  ...BidModalCont"
    "ent_trade\n}\n\nfragment accounts_url on AccountType {\n  address\n  u"
    "ser {\n    publicUsername\n    id\n  }\n}\n\nfragment assetInputType on"
    " AssetType {\n  tokenId\n  assetContract {\n    address\n    chain\n  "
    "  id\n  }\n}\n\nfragment asset_display_name on AssetType {\n  tokenId\n"
    "  name\n}\n\nfragment asset_url on AssetType {\n  assetContract {\n   "
    " address\n    chain\n    id\n  }\n  tokenId\n}\n\nfragment collection_ur"
    "l on CollectionType {\n  slug\n}\n\nfragment itemEvents_data on Asset"
    "Type {\n  assetContract {\n    address\n    chain\n    id\n  }\n  token"
    "Id\n}\n\nfragment itemEvents_viewItem_data on AssetType {\n  ...itemE"
    "vents_data\n  collection {\n    ...verification_data\n    id\n  }\n  i"
    "sReportedSuspicious\n}\n\nfragment orderLink_data on OrderV2Type {\n "
    " makerAssetBundle {\n    assetQuantities(first: 30) {\n      edges "
    "{\n        node {\n          asset {\n            externalLink\n     "
    "       collection {\n              externalUrl\n              id\n  "
    "          }\n            id\n          }\n          id\n        }\n   "
    "   }\n    }\n    id\n  }\n}\n\nfragment quantity_data on AssetQuantityT"
    "ype {\n  asset {\n    decimals\n    id\n  }\n  quantity\n}\n\nfragment qu"
    "antity_remaining on OrderV2Type {\n  makerAsset: makerAssetBundle "
    "{\n    assetQuantities(first: 1) {\n      edges {\n        node {\n  "
    "        asset {\n            decimals\n            id\n          }\n "
    "         quantity\n          id\n        }\n      }\n    }\n    id\n  }"
    "\n  takerAsset: takerAssetBundle {\n    assetQuantities(first: 1) {"
    "\n      edges {\n        node {\n          asset {\n            decim"
    "als\n            id\n          }\n          quantity\n          id\n  "
    "      }\n      }\n    }\n    id\n  }\n  remainingQuantity\n  side\n}\n\nfr"
    "agment verification_data on CollectionType {\n  isMintable\n  isSaf"
    "elisted\n  isVerified\n}\n\nfragment wallet_accountKey on AccountType"
    " {\n  address\n}\n"
)
